SELECT ANIMAL_ID,ANIMAL_TYPE,NAME
FROM ANIMAL_INS
WHERE SEX_UPON_INTAKE NOT IN ('Neutered Male', 'Spayed Female')
  AND ANIMAL_ID IN (
    SELECT ANIMAL_ID
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME IN ('Neutered Male', 'Spayed Female')
)
ORDER BY ANIMAL_ID