SELECT YEAR(SALES_DATE), MONTH(SALES_DATE),GENDER, COUNT(DISTINCT S.USER_ID) USERS
FROM USER_INFO I
JOIN ONLINE_SALE S
ON I.USER_ID = S.USER_ID
WHERE I.GENDER IN (0,1)
GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE),I.GENDER
ORDER BY YEAR(SALES_DATE),MONTH(SALES_DATE),GENDER