SELECT 
    YEAR(sales_date) AS YEAR ,
    MONTH(sales_date) AS MONTH, 
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(
    COUNT(DISTINCT I.USER_ID)*1.0 /
        (SELECT COUNT(USER_ID)
        FROM USER_INFO 
        WHERE YEAR(JOINED) = 2021),1
        ) AS PUCHASED_RATIO
    
FROM ONLINE_SALE S
JOIN USER_INFO I
ON S.USER_ID = I.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY MONTH
ORDER BY YEAR ,MONTH